# Generated by Django 4.2.6 on 2023-10-15 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msgid', models.CharField(max_length=255)),
                ('sent_time', models.DateTimeField()),
                ('received_time', models.DateTimeField()),
                ('sender', models.EmailField(max_length=254)),
                ('receiver', models.TextField()),
                ('cc', models.TextField()),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('folder_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.emailfolder')),
            ],
        ),
        migrations.DeleteModel(
            name='MailboxCredentials',
        ),
    ]
