# Generated by Django 4.2.6 on 2023-10-15 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_emailfolder_emailmessage_delete_mailboxcredentials'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailfolder',
            old_name='folder_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='emailmessage',
            old_name='folder_name',
            new_name='folder',
        ),
        migrations.RenameField(
            model_name='emailmessage',
            old_name='received_time',
            new_name='received_date',
        ),
        migrations.RenameField(
            model_name='emailmessage',
            old_name='sent_time',
            new_name='sent_date',
        ),
    ]
