# Generated by Django 4.2.6 on 2023-10-15 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_folder_name_emailfolder_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailmessage',
            name='folder',
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='folder_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='EmailFolder',
        ),
    ]
