# Generated by Django 4.2.6 on 2023-10-16 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_emailmessage_folder_emailmessage_folder_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmessage',
            name='folder_name',
            field=models.CharField(default='Default Folder', max_length=255),
        ),
    ]
