# Generated by Django 4.2.6 on 2023-10-16 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_emailmessage_folder_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmessage',
            name='folder_name',
            field=models.CharField(max_length=255),
        ),
    ]
